In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

# --- 1. 5일차에 만든 모델 클래스 (복사/붙여넣기) ---
class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleMLP, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.layer1(x)
        out = self.relu(out)
        out = self.layer2(out)
        out = self.sigmoid(out)
        return out

# --- 2. 데이터 준비 (2진 분류용 가상 데이터) ---
# 입력 (Feature 2개): [0,0], [0,1], [1,0], [1,1]
x_train = torch.tensor([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
], dtype=torch.float32)

# 정답 (Label 1개): 0, 1, 1, 0 (XOR 문제)
# (주의!) BCELoss는 타겟(y_train)도 float 타입이어야 합니다.
y_train = torch.tensor([
    [0.0],
    [1.0],
    [1.0],
    [0.0]
], dtype=torch.float32)

# --- 3. 모델, 손실함수, 옵티마이저 정의 (6일차 핵심) ---
model=SimpleMLP(input_size=2, hidden_size=4, output_size=1)

# 손실 함수: nn.BCELoss()로 변경
loss_fn=nn.BCELoss()

# 옵티마이저: optim.Adam()으로 변경 (lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.01)

print("--- 학습 시작 전 모델 예측 ---")
initial_pred=model(x_train)
print(initial_pred.data)

# --- 4. 학습 루프 (Training Loop) 실행
epochs = 3000

for epoch in range(epochs+1):
    # 1. 순전파 (Forward Pass)
    prediction = model(x_train)

    # 2. 손실 계산 (BCELoss 사용)
    loss = loss_fn(prediction, y_train)

    # 3. 기울기 초기화
    optimizer.zero_grad()

    # 4. 역전파 (Backward Pass)
    loss.backward()

    # 5. 파라미터 업데이트 (Adam 사용)
    optimizer.step()

    if epoch % 200 == 0:
        print(f"Epoch {epoch:5d}/{epochs} | Loss: {loss.item():.4f}")

print("\n--- 학습 완료 후 모델 예측 ---")
final_pred = model(x_train)

# 0.5를 기준으로 0 또는 1로 변환하여 정답과 비교
# .round()는 0.5를 기준으로 반올림해줍니다.
final_pred_labels = final_pred.round().data

print("예측 확률값:")
print(final_pred.data)
print("\n최종 예측 레이블 (0.5 기준):")
print(final_pred_labels)
print("\n실제 정답 레이블:")
print(y_train)

--- 학습 시작 전 모델 예측 ---
tensor([[0.4698],
        [0.5082],
        [0.4779],
        [0.4831]])
Epoch     0/3000 | Loss: 0.6774
Epoch   200/3000 | Loss: 0.0960
Epoch   400/3000 | Loss: 0.0206
Epoch   600/3000 | Loss: 0.0087
Epoch   800/3000 | Loss: 0.0048
Epoch  1000/3000 | Loss: 0.0030
Epoch  1200/3000 | Loss: 0.0021
Epoch  1400/3000 | Loss: 0.0015
Epoch  1600/3000 | Loss: 0.0011
Epoch  1800/3000 | Loss: 0.0009
Epoch  2000/3000 | Loss: 0.0007
Epoch  2200/3000 | Loss: 0.0006
Epoch  2400/3000 | Loss: 0.0005
Epoch  2600/3000 | Loss: 0.0004
Epoch  2800/3000 | Loss: 0.0003
Epoch  3000/3000 | Loss: 0.0003

--- 학습 완료 후 모델 예측 ---
예측 확률값:
tensor([[9.3068e-05],
        [9.9978e-01],
        [9.9980e-01],
        [5.7923e-04]])

최종 예측 레이블 (0.5 기준):
tensor([[0.],
        [1.],
        [1.],
        [0.]])

실제 정답 레이블:
tensor([[0.],
        [1.],
        [1.],
        [0.]])
